# Tenant domain
domain: umich.edu

# This should be an Azure AD 2.0 client that's been registered at
# https://apps.dev.microsoft.com/ and granted "Application Permissions"
# (not "Delegated Permissions") User.Read.All and Files.Read.All for
# the tenant domain by visiting
# https://login.microsoftonline.com/common/adminconsent?client_id=foo&state=12345&redirect_uri=http://localhost/myapp/permissions
# while logged in as an admin. It's fine to have the app redirect pointing
# at an unusable URL, becase the redirect doesn't carry any useful information.
client_id: foo
client_secret: bar

# Request timeout
timeout: 6
