#!/usr/bin/env python

# This file is part of onedrive-magic and distributed under the terms of the
# MIT license. See COPYING.

from __future__ import (absolute_import, division, print_function)
__metaclass__ = type

import json
import sys

import yaml

from util import cli, quickxorhash

cli = cli.CLI(['user', 'action'])
client = cli.client

drives = client.list_drives(cli.args.user)

if cli.args.action == 'list-drives':
    if cli.args.verbose:
        json.dump(drives, sys.stdout, indent = 2)
    else:
        for d in drives:
            print(d['id'])

elif cli.args.action == 'list-items':
    items = client.expand_items([drive['root'] for drive in drives])

    if cli.args.verbose:
        json.dump(items, sys.stdout, indent = 2)
    else:
        for item in items:
            print(item['fullpath'])

elif cli.args.action == 'download-items':
    items = client.expand_items([drive['root'] for drive in drives])
    for item in items:
        if 'file' in item:
            dest = '/var/tmp/' + cli.args.user + '/' + item['fullpath']
            print('Downloading {}...'.format(item['fullpath']))
            h = client.download_file(item['parentReference']['driveId'], item['id'], dest, item['file']['hashes']['quickXorHash'])
            print('MSoft hash: {}'.format(item['file']['hashes']['quickXorHash']))
            print('Local hash: {}'.format(h))

else:
    print('Unsupported action {}'.format(cli.args.action))
