#!/usr/bin/env python

# This file is part of onedrive-magic and distributed under the terms of the
# MIT license. See COPYING.

from __future__ import (absolute_import, division, print_function)
__metaclass__ = type

import json
import sys

import yaml

from util import cli, quickxorhash

cli = cli.CLI(['user', 'action'])
client = cli.client

drives = client.list_drives(cli.args.user)

if cli.args.action == 'list-drives':
    json.dump(drives, sys.stdout, indent = 2)

elif cli.args.action == 'list-items':
    items = client.expand_items([drive['root'] for drive in drives])
    json.dump(items, sys.stdout, indent = 2)

else:
    print('Unsupported action {}'.format(cli.args.action))
