#!/usr/bin/env python

# This file is part of onedrive-magic and distributed under the terms of the
# MIT license. See COPYING.

from __future__ import (absolute_import, division, print_function)
__metaclass__ = type

import json
import sys

from kitchen.text.converters import getwriter

from util import cli, quickxorhash

sys.stdout = getwriter('utf8')(sys.stdout)

cli = cli.CLI(['file', 'action'])
client = cli.client

with open(cli.args.file, 'rb') as f:
    inlist = json.load(f)

if cli.args.action == 'list-items':
    for item in inlist:
        print(item['fullpath'])
else:
    print('Unsupported action {}'.format(cli.args.action))
