#!/usr/bin/env python

# This file is part of onedrive-magic and distributed under the terms of the
# MIT license. See COPYING.

from __future__ import (absolute_import, division, print_function)
__metaclass__ = type

import json
import sys

import yaml

from util import cli, quickxorhash

cli = cli.CLI(['--dest', 'drive', 'file'])
client = cli.client

if cli.args.dest:
    dest = cli.args.dest
else:
    dest = '/var/tmp/' + cli.args.file

h = client.download_file(cli.args.drive, cli.args.file, dest)
