#!/usr/bin/env python

# This file is part of ODM and distributed under the terms of the
# MIT license. See COPYING.

from __future__ import (absolute_import, division, print_function)
__metaclass__ = type

import json
import sys

import yaml

from util import cli, quickxorhash

cli = cli.CLI(['action'])
client = cli.client

if cli.args.action == 'list-users':
    print(json.dumps(client.list_users(), indent = 2))

else:
    print('Unsupported action {}'.format(cli.args.action), file = sys.stderr)
    sys.exit(1)
