#!/usr/bin/env python

# This file is part of onedrive-magic and distributed under the terms of the
# MIT license. See COPYING.

from __future__ import (absolute_import, division, print_function)
__metaclass__ = type

import argparse

from util import quickxorhash

parser = argparse.ArgumentParser()
parser.add_argument('file')
args = parser.parse_args()

q = quickxorhash.QuickXORHash()
with open(args.file, 'rb') as f:
    while True:
        chunk = f.read(65536)
        if chunk:
            q.update(bytearray(chunk))
        else:
            break
print(q.finalize())
