#!/usr/bin/env python3

# This file is part of ODM and distributed under the terms of the
# MIT license. See COPYING.

import argparse

from odm import quickxorhash

parser = argparse.ArgumentParser()
parser.add_argument('file')
args = parser.parse_args()

q = quickxorhash.QuickXORHash()
print(q.hash_file(args.file))
